LEVEL = ../..
LIBRARYNAME = SaibHelper
include $(LEVEL)/Makefile.common

CXX.Flags += -I/home/user/Documents/llvm-3.4/tools/lldb/include/ -I/home/user/Documents/llvm-3.4/tools/clang/include/ -I/home/user/Documents/libelf-0.8.13-install/include/